# -*- coding: utf-8 -*-
"""README 展示素材生成器

从 renderer/spritesheet.webp 生成:
  docs/animations.png  — 全部动画的一览网格(带标签)
  docs/demo.gif        — 循环播放几个代表动画的 GIF

用 30_Tools/py311 环境运行:
  python assets/make_preview.py
"""
import os
from PIL import Image, ImageDraw, ImageFont

HERE = os.path.dirname(os.path.abspath(__file__))
SHEET = os.path.join(HERE, "..", "renderer", "spritesheet.webp")
DOCS = os.path.join(HERE, "..", "docs")

CW, CH = 192, 208  # 精灵格尺寸

BG = (245, 244, 239)      # 奶白底(明暗主题下都清晰)
FG = (60, 56, 52)
SUB = (140, 134, 128)
CARD = (255, 255, 255)

# (名称, 行, 帧数, 每帧毫秒, 说明)
ANIMS = [
    ("idle", 0, 6, 200, "waiting around"),
    ("running-right", 1, 8, 120, "strolling"),
    ("running-left", 2, 8, 120, "strolling back"),
    ("waving", 3, 4, 160, "hello!"),
    ("jumping", 4, 5, 150, "task done"),
    ("failed", 5, 8, 150, "an error"),
    ("waiting", 6, 6, 160, "needs your call"),
    ("running", 7, 6, 130, "busy (legacy)"),
    ("review", 8, 6, 170, "thinking"),
    ("typing", 9, 6, 130, "Claude is working"),
    ("flower", 10, 6, 260, "for you"),
    ("coffee", 11, 6, 340, "coffee break"),
    ("water", 12, 6, 340, "hydrating"),
    ("fries", 13, 6, 290, "lunch time"),
    ("sausage", 14, 6, 320, "dinner time"),
    ("gaming", 15, 6, 150, "fullscreen app"),
    ("backflip", 16, 8, 100, "celebrating"),
    ("doze", 17, 6, 550, "3 min idle"),
    ("sleep", 18, 6, 400, "8 min idle"),
    ("stretch", 19, 6, 300, "break time"),
    ("phone", 20, 6, 290, "doomscrolling"),
    ("petted", 21, 6, 220, "hover to pet"),
]

# GIF 里循环播放的动画(名称, 循环几遍)
GIF_SEQ = [
    ("waving", 2), ("typing", 3), ("coffee", 1), ("running-right", 2),
    ("backflip", 2), ("fries", 1), ("petted", 2), ("sleep", 2),
]


def load_font(size, bold=False, cjk=False):
    if cjk:
        names = ("msyhbd.ttc", "msyh.ttc", "simhei.ttf") if bold else ("msyh.ttc", "simhei.ttf", "simsun.ttc")
    else:
        names = ("arialbd.ttf", "seguisb.ttf") if bold else ("arial.ttf", "segoeui.ttf")
    for name in names:
        try:
            return ImageFont.truetype(name, size)
        except Exception:
            continue
    return ImageFont.load_default()


def frame(sheet, row, col):
    return sheet.crop((col * CW, row * CH, (col + 1) * CW, (row + 1) * CH))


def trim_box(sheet):
    """所有帧的公共内容包围盒, 保证缩放后各动画对齐"""
    bbox = sheet.getbbox()
    return bbox


def make_grid(sheet):
    cols = 6
    cell_w, cell_h = 132, 150
    pad_top = 64
    rows = (len(ANIMS) + cols - 1) // cols
    W = cols * cell_w + 24
    H = pad_top + rows * cell_h + 16
    img = Image.new("RGB", (W, H), BG)
    d = ImageDraw.Draw(img)

    f_title = load_font(24, bold=True)
    f_name = load_font(13, bold=True)
    f_desc = load_font(11)

    d.text((16, 12), "Claw'd — animation set", font=f_title, fill=FG)
    d.text((16, 40), f"{len(ANIMS)} animations, all generated by assets/make_clawd_sprites.py",
           font=f_desc, fill=SUB)

    for i, (name, row, frames, _ms, desc) in enumerate(ANIMS):
        cx = 12 + (i % cols) * cell_w
        cy = pad_top + (i // cols) * cell_h
        d.rounded_rectangle([cx + 4, cy + 4, cx + cell_w - 8, cy + cell_h - 10],
                            radius=8, fill=CARD)
        # 取一个有代表性的帧(中间帧动作最明显)
        fr = frame(sheet, row, min(frames - 1, frames // 2))
        fr = fr.resize((int(CW * 0.42), int(CH * 0.42)), Image.NEAREST)
        img.paste(fr, (cx + (cell_w - 12 - fr.width) // 2 + 4, cy + 10), fr)
        d.text((cx + cell_w // 2, cy + cell_h - 40), name, font=f_name, fill=FG, anchor="mt")
        d.text((cx + cell_w // 2, cy + cell_h - 26), desc, font=f_desc, fill=SUB, anchor="mt")

    return img


def make_gif(sheet):
    scale = 0.62
    fw, fh = int(CW * scale), int(CH * scale)
    W, H = fw + 24, fh + 24
    frames, durations = [], []
    lookup = {a[0]: a for a in ANIMS}

    for name, loops in GIF_SEQ:
        _n, row, count, ms, _d = lookup[name]
        for _ in range(loops):
            for c in range(count):
                canvas = Image.new("RGB", (W, H), BG)
                fr = frame(sheet, row, c).resize((fw, fh), Image.NEAREST)
                canvas.paste(fr, (12, 12), fr)
                frames.append(canvas.convert("P", palette=Image.ADAPTIVE, colors=64))
                durations.append(ms)
    return frames, durations


def main():
    os.makedirs(DOCS, exist_ok=True)
    sheet = Image.open(SHEET).convert("RGBA")

    grid = make_grid(sheet)
    grid_path = os.path.abspath(os.path.join(DOCS, "animations.png"))
    grid.save(grid_path, "PNG")
    print("saved:", grid_path, grid.size)

    frames, durations = make_gif(sheet)
    gif_path = os.path.abspath(os.path.join(DOCS, "demo.gif"))
    frames[0].save(gif_path, save_all=True, append_images=frames[1:],
                   duration=durations, loop=0, optimize=True)
    size_kb = os.path.getsize(gif_path) / 1024
    print(f"saved: {gif_path} ({len(frames)} frames, {size_kb:.0f} KB)")


if __name__ == "__main__":
    main()


# ── docs/states.png — labelled grid of real window captures ──────────

STATE_SHOTS = [
    ("shot-usage", "Click → today's cost", "点击查看今日花费"),
    ("shot-waiting", "Claude needs a decision", "Claude 等你拍板"),
    ("shot-typing", "Claude is working", "Claude 正在工作"),
    ("shot-sessions", "Several sessions at once", "多会话徽章"),
    ("shot-flower", "Idle: brings a flower", "空闲：举小花"),
    ("shot-sleep", "8 min idle: nightcap", "闲置 8 分钟：睡帽"),
]


def make_states():
    import glob
    shots = []
    for name, en, zh in STATE_SHOTS:
        p = os.path.join(DOCS, name + ".png")
        if os.path.exists(p):
            shots.append((Image.open(p).convert("RGB"), en, zh))
    if not shots:
        print("no shot-*.png captures found, skipping states.png")
        return

    cols = 3
    cw = max(s[0].width for s in shots) + 16
    ch = max(s[0].height for s in shots) + 44
    rows = (len(shots) + cols - 1) // cols
    img = Image.new("RGB", (cols * cw + 16, rows * ch + 16), BG)
    d = ImageDraw.Draw(img)
    f_en = load_font(13, bold=True)
    f_zh = load_font(12, cjk=True)

    for i, (shot, en, zh) in enumerate(shots):
        cx = 8 + (i % cols) * cw
        cy = 8 + (i // cols) * ch
        d.rounded_rectangle([cx + 4, cy + 4, cx + cw - 8, cy + ch - 8], radius=8, fill=CARD)
        img.paste(shot, (cx + (cw - shot.width) // 2, cy + 10))
        base = cy + ch - 34
        d.text((cx + cw // 2, base), en, font=f_en, fill=FG, anchor="mt")
        d.text((cx + cw // 2, base + 15), zh, font=f_zh, fill=SUB, anchor="mt")

    path = os.path.abspath(os.path.join(DOCS, "states.png"))
    img.save(path, "PNG")
    print("saved:", path, img.size)


make_states()
